<h3><a href="http://www.bostonbikes.org/events/bike-fridays/convoy-routes/" title="Find out more">Bay State Bike Week 2012</a></h3>
<p><strong>May 14-20th</strong> - Organized by the City of Boston and Mayor Menino. The celebration day takes place on Friday May 18th, culminating in a festival held at City Hall Plaza. The festival features nine group rides on different routes throughout the city, vendors, expos, free breakfast and refreshments in addition to complementary bike tune-ups and examinations. <a href="http://www.surveymonkey.com/s/GZVLXX6" title="Register for bike week"> Register for bike week now!</a> </p>

<h3><a href="http://www.bikefridays.org/" title="Find out more">Bike Fridays</a></h3>
<p><strong>May 18th</strong> - Organized by the City of Boston and Mayor Menino. May 18th also marks the kick off of Boston's summer Friday ride series. One Friday a month from May through August the city celebrates bicycle commuters and riders with live music, free breakfast and coffee at City Hall Plaza. This summer's dates include: May 18th, June 15th, July 27th, and August 31st.</p>

<h3><a href="http://www.cyclekids.org/events/2nd-annual-breakaway-ride" title="For more info and to register">Cycle Kids "Breakaway Fundraiser"</a></h3>
<p><strong>May 20th</strong> - Organized by nonprofit Cycle Kids. Cycle Kids is a Cambridge-based nonprofit dedicated to combating childhood obesity through cycling education programs. The organization is hosting its second annual fundraiser ride in Lincoln, MA on Saturday, May 20. The event includes three distance options, all starting and finishing at the deCordova Sculpture Park and Museum, where participants will celebrate with a post-ride bluegrass music and a complementary cookout prepared by Paul O'Connell, chef of Chez Henri and Chef Danny, of the Atlantic Fish Company.</p>

<h3><a href="http://www.livablestreets.info/event/rush-hour-race" title="Find out more">"Rush Hour Race"</a></h3>
<p><strong>May 14th</strong> - Organized by Livable Streets, Somerville Bicycle Committee, and Cambridge Bicycle Committee. The event, which takes place on Monday May 14th, challenges commuters to test out the fastest transportation mode from Somerville's Davis Square to Cambridge's Kendall Square. Diver vs. Cyclist vs. 'T' Rider will compete from start to finish.</p>

<h3><a href="http://massbike.org/blog/2012/03/08/save-the-date-beyond-the-spandex-is-coming/" title="Find out more">"Beyond the Spandex"</a></h3>
<p><strong>May 3rd</strong> - Organized by MassBike and the Westin Waterfront. MassBike, a coalition dedicated the encouraging a bicycle-friendly environment, is hosting Bike Night: Beyond the Spandex to showcase cycling's functional and fashionable urban cycling clothing and gear on May 3rd from 6:30-9pm at the Weston Waterfront in Boston. The event, which costs $75 a person, features cocktails, hors d'oeuvres, a full dinner and with cap the evening off with a fashion show and raffle. </p>
